import type { Metadata } from 'next';
import { LegalContent, type LegalSectionData } from '@/components/LegalContent';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms governing use of the Chambé platform.',
};

const SECTIONS: LegalSectionData[] = [
  {
    heading: 'The Service',
    paragraphs: [
      'Chambé helps homeowners in Toronto and the Greater Toronto Area request an AI-generated price estimate for home improvement and repair work, and connects them with an independent, vetted local contractor to complete that work.',
    ],
  },
  {
    heading: 'Independent Contractors',
    paragraphs: [
      'Contractors matched through Chambé are independent businesses, not employees or agents of Chambé. Chambé is not a party to, and is not responsible for, the contract for work between you and the contractor. Any agreement about scope, price, timeline, materials, or workmanship is between you and the contractor directly.',
    ],
  },
  {
    heading: 'Estimates',
    paragraphs: [
      'Price estimates generated by Chambé are provided for informational purposes only, based on the information you provide, and are not a binding quote, offer, or guarantee of final price. Final pricing is agreed between you and the contractor.',
    ],
  },
  {
    heading: 'User Responsibilities',
    paragraphs: [
      'You agree to provide accurate information when requesting an estimate, to use the Service only for lawful purposes, and not to misuse the Service to submit false job requests.',
    ],
  },
  {
    heading: 'No Warranty',
    paragraphs: [
      'The Service is provided "as is" without warranties of any kind, express or implied, including as to the accuracy of estimates or the quality of work performed by any contractor.',
    ],
  },
  {
    heading: 'Limitation of Liability',
    paragraphs: [
      "To the maximum extent permitted by law, Chambé is not liable for any indirect, incidental, or consequential damages arising from your use of the Service or from work performed by a matched contractor. Chambé's total liability for any claim arising from the Service is limited to the amount, if any, you paid to Chambé directly.",
    ],
  },
  {
    heading: 'Termination',
    paragraphs: ['We may suspend or terminate access to the Service at any time, including for violation of these Terms.'],
  },
  {
    heading: 'Governing Law',
    paragraphs: [
      'These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein.',
    ],
  },
  {
    heading: 'Changes to These Terms',
    paragraphs: [
      'We may update these Terms from time to time. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.',
    ],
  },
  {
    heading: 'Contact Us',
    paragraphs: ['Questions about these Terms can be sent to hello@chambe.ca.'],
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-20">
      <h1 className="text-4xl font-bold tracking-tight text-foreground">Terms of Service</h1>
      <p className="mt-3 text-sm text-foreground/50">Last updated: August 2026</p>

      <p className="mt-8 text-sm leading-relaxed text-foreground/75">
        These Terms of Service (&quot;Terms&quot;) govern your use of chambe.ca and the Chambé
        service (the &quot;Service&quot;), operated by Chambé Inc. (&quot;Chambé,&quot;
        &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By using the Service, you agree to
        these Terms.
      </p>

      <LegalContent sections={SECTIONS} />
    </div>
  );
}
